apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shoe.fullname" . }}
  labels:
    {{- include "shoe.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "shoe.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "shoe.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.targetport }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
